#!/usr/bin/env bash
# Renders a PR body from run artifacts.
#
#   pr-body.sh <run-id> <repo> [--with-links]
#
# Two passes are required: gh pr create cannot forward-reference PRs that do not exist yet.
# Pass 1 omits --with-links; pass 2 re-renders with sibling PR numbers from run.json.
set -euo pipefail
ROOT="${PROFITIFY_ROOT:-/Users/sadatahmed/Personal/Profitify}"
RUN_ID="${1:?usage: pr-body.sh <run-id> <repo> [--with-links]}"
REPO="${2:?missing repo}"; WITH_LINKS="${3:-}"
RUN="$ROOT/.runs/$RUN_ID"
ITER=$(jq -r --arg r "$REPO" '.repos[$r].iteration' "$RUN/run.json")

full_name() { case "$1" in backend) echo sahmedcse/profitify-backend;; web) echo sahmedcse/profitify-web;; ops) echo sahmedcse/profitify-ops;; esac; }

echo "## What this changes"
echo ""
sed -n "/^## repo: $REPO\$/,/^## repo: /p" "$RUN/plan.md" | sed '1d;$ {/^## repo: /d;}'

WT="$ROOT/.worktrees/$RUN_ID/$REPO"
if [ -d "$WT" ]; then
  COMMITS=$(git -C "$WT" log --pretty='- `%h` %s' origin/main..HEAD 2>/dev/null || true)
  if [ -n "$COMMITS" ]; then
    echo ""
    echo "## Commits"
    echo ""
    echo "$COMMITS"
  fi
fi

if [ "$WITH_LINKS" = "--with-links" ]; then
  echo ""
  echo "## Coordinated change — run \`$RUN_ID\`"
  echo ""
  N=$(jq -r '[.repos[] | select(.pr != null)] | length' "$RUN/run.json")
  echo "One of $N PRs for a single feature. All share the branch \`$(jq -r .branch "$RUN/run.json")\`."
  echo ""
  echo "| Order | Repo | PR |"
  echo "|---|---|---|"
  i=0
  for r in $(jq -r '.merge_order[]' "$RUN/contract.json"); do
    PR=$(jq -r --arg r "$r" '.repos[$r].pr // empty' "$RUN/run.json")
    [ -z "$PR" ] && continue
    i=$((i+1))
    echo "| $i | profitify-$r | $(full_name "$r")#$PR |"
  done
  echo ""
  echo "> Merge in this order. **Merging any of these deploys to production** — see below."
fi

cat <<'EOF'

## Deploy impact

| Repo | What merging to `main` does |
|---|---|
| backend | Builds and pushes 8 ECR images, then `aws lambda update-function-code` on all 8 `prod-*` functions |
| ops | Deploys every CDK stack with no approval prompt |
| web | Syncs the built site to the prod bucket and invalidates the CDN. **No `paths-ignore`** |

EOF

echo "## Verification — local gate (CI-equivalent)"
echo ""
GJSON="$RUN/gate/$REPO.iter$ITER.json"
if [ -f "$GJSON" ]; then
  echo "Gate status: **$(jq -r '.status' "$GJSON")** (iteration $ITER)"
  echo ""
  echo "| Step | Result | Seconds |"
  echo "|---|---|---|"
  jq -r '.steps[] | "| \(.name)\(if .advisory then " _(advisory)_" else "" end) | \(.result) | \(.seconds // "-") |"' "$GJSON"
fi

cat <<'EOF'

### Known local↔CI divergences

- **backend**: local `golangci-lint` is 2.4.0, CI pins v2.11 — lint ran advisory-only locally.
- **ops**: local Node 24, CI Node 22.
- **ops**: `cdk diff` needs credentials and did **not** run locally. **Read the CDK Diff bot
  comment on this PR before marking it ready.**
EOF

RJSON="$RUN/review/$REPO.iter$ITER.json"
if [ -f "$RJSON" ]; then
  COUNT=$(jq '[.findings[]|select(.severity=="advisory")]|length' "$RJSON")
  if [ "$COUNT" -gt 0 ]; then
    echo ""
    echo "## Reviewer notes (non-blocking)"
    echo ""
    jq -r '.findings[] | select(.severity=="advisory") | "- **\(.file):\(.line)** — \(.problem)"' "$RJSON"
  fi
fi

echo ""
echo "---"
echo "🤖 Generated by \`/feature\` (profitify-agents), run \`$RUN_ID\`. Review the CI signal — including the CDK Diff comment on ops PRs — before merging; merging deploys to production."
